const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),base=require('./dist/world.js'),exp=require('./dist/expansion-world.js');
const w=exp.expand(base.createWorld());exp.apply(w,{});
assert(base.blocked(w.meadow,31*32+16,13*32+16));assert(base.blocked(w.riverbank,20*32+16,4*32+16));
exp.apply(w,{bridge:true,seal:true});
function reachable(m,start){const seen=new Set(),q=[start];while(q.length){const [x,y]=q.shift(),key=x+','+y;if(seen.has(key)||base.blocked(m,x*32+16,y*32+16))continue;seen.add(key);for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]])q.push([x+dx,y+dy]);}return seen;}
for(const [id,start]of [['meadow',[2,13]],['riverbank',[2,16]],['cavern',[12,18]]]){const m=w[id],seen=reachable(m,start);for(const p of m.portals){assert(seen.has(Math.floor((p.x+p.w/2)/32)+','+Math.floor((p.y+p.h/2)/32)),`Unreachable ${id}->${p.to}`);assert(!base.blocked(w[p.to],p.tx,p.ty),`Blocked arrival ${id}->${p.to}`);}for(const o of [...m.npcs,...m.objects.filter(o=>['seal','beacon','cache','bridge','fish','crystals'].includes(o.type))])assert([...seen].some(k=>{const [x,y]=k.split(',').map(Number);return Math.hypot(x*32+16-o.x,y*32+16-o.y)<43}),`Unreachable ${id} ${o.type||o.name}`);}
const elements={},events={},ctx=new Proxy({},{get:(t,k)=>k in t?t[k]:()=>{}});function el(id=''){return elements[id]??={innerHTML:'',textContent:'',style:{},dataset:{},clientWidth:390,clientHeight:844,classList:{add(){},remove(){}},getContext:()=>ctx,addEventListener(n,f){events[id+':'+n]=f},setAttribute(){},querySelector:()=>({focus(){}}),append(){},remove(){},focus(){},getBoundingClientRect:()=>({left:0,top:0,width:120,height:120})};}
let saved;const sandbox={World:{...base,createWorld:()=>exp.expand(base.createWorld())},ExpansionWorld:exp,GameAudio:{sfx(){},unlock:async()=>true,settings:{music:false,effects:true,volume:.3}},console,Date,Math,JSON,innerWidth:390,performance:{now:()=>0},requestAnimationFrame(){},setInterval(){},setTimeout(){},clearTimeout(){},addEventListener(){},matchMedia:()=>({matches:true}),navigator:{getGamepads:()=>[]},localStorage:{getItem:()=>null,setItem(k,v){saved=v}},document:{getElementById:el,querySelector:()=>el('query'),querySelectorAll:()=>[],createElement:()=>el('new'),addEventListener(){}}};vm.createContext(sandbox);for(const file of ['play.js','interaction.js','expansion.js'])vm.runInContext(fs.readFileSync('dist/'+file,'utf8'),sandbox);const run=s=>vm.runInContext(s,sandbox);
run("map=worlds.meadow;player.x=29*32+16;player.y=13*32+16;interact()");assert.equal(run("expeditionAction('bridge')"),false);run("state.wood=12;state.team.push('Emberkin')");assert(run("expeditionAction('bridge')"));assert.equal(run('state.wood'),0);assert(!run('blocked(worlds.meadow,31*32+16,13*32+16)'));run('dialog=true');assert.equal(run("expeditionAction('bridge')"),false);
run("map=worlds.riverbank;player.x=20*32+16;player.y=6*32+16;interact()");assert.equal(run("expeditionAction('seal')"),false);run("state.team.push('Lunamoth')");assert(run("expeditionAction('seal')"));
run("map=worlds.cavern;player.x=12*32+16;player.y=7*32+16;state.crystals=5;interact()");const coins=run('state.coins');assert(run("expeditionAction('beacon')"));assert.equal(run('state.coins'),coins+120);assert.equal(run('state.crystals'),0);assert.equal(run('resourceInfo.berries.amount'),4);run('applyBlessing()');assert.equal(run('resourceInfo.berries.amount'),4);run('dialog=true');assert.equal(run("expeditionAction('beacon')"),false);
run("close();map=worlds.riverbank;player.x=27*32+16;player.y=19*32+16;state.fish=3;interact()");assert(run("expeditionAction('nell')"));assert.equal(run('state.fish'),0);run('dialog=true');assert.equal(run("expeditionAction('nell')"),false);run("close();player.x=6*32+16;player.y=27*32+16;interact()");const afterCache=run('state.coins');run('interact()');assert.equal(run('state.coins'),afterCache);assert(JSON.parse(saved).exploration.beacon);
run('dialog=false;frame(16.67)');
console.log('PASS: expansion routes and resource reachability; bridge/companion gates; one-time resource costs and rewards; beacon bonus stays +1; fisher trade; hidden cache; progress persistence; expanded rendering frame.');
