const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const World=require('./dist/world.js'),{T,createWorld,blocked,move,portalAt}=World,maps=createWorld();
for(const m of Object.values(maps)){
  for(const p of m.portals){assert(maps[p.to]);assert(!blocked(maps[p.to],p.tx,p.ty),`Blocked arrival: ${m.id} -> ${p.to}`);assert(!blocked(m,p.x+p.w/2,p.y+p.h/2),`Blocked entrance ${m.id}`);}
  const start=m.id==='valley'?{x:208,y:368}:m.id==='meadow'?{x:80,y:432}:m.id==='grove'?{x:496,y:784}:{x:240,y:368};
  const seen=new Set(),queue=[[Math.floor(start.x/T),Math.floor(start.y/T)]];
  while(queue.length){const [x,y]=queue.shift(),k=x+','+y;if(seen.has(k)||blocked(m,x*T+16,y*T+16))continue;seen.add(k);for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]])queue.push([x+dx,y+dy]);}
  for(const p of m.portals)assert(seen.has(Math.floor((p.x+p.w/2)/T)+','+Math.floor((p.y+p.h/2)/T)),`Unreachable portal ${m.id} -> ${p.to}`);
  for(const o of [...m.npcs,...m.objects.filter(o=>['workbench','chest','berries','crystals','fish'].includes(o.type))])assert([...seen].some(k=>{const [x,y]=k.split(',').map(Number);return Math.hypot(x*T+16-o.x,y*T+16-o.y)<43}),`Unreachable interaction ${m.id} ${o.name||o.type}`);
}
let p={x:208,y:310};move(maps.valley,p,0,-400);assert(p.y>=263,'Cannot walk through building');assert(portalAt(maps.valley,p)?.to==='cottage');p={x:21*T,y:5*T};move(maps.meadow,p,200,0);assert(p.x<22*T-6,'Cannot cross pond');
const events={},timeouts=[],els={},ctx=new Proxy({},{get:(target,key)=>key in target?target[key]:()=>{}});function el(id=''){return els[id]??=( {id,innerHTML:'',textContent:'',style:{},dataset:{},clientWidth:960,clientHeight:640,classList:{add(){},remove(){}},getContext:()=>ctx,addEventListener(n,f){events[id+':'+n]=f},querySelector(){return {focus(){}}},append(){},remove(){},focus(){},setPointerCapture(){},getBoundingClientRect(){return {left:0,top:0,width:132,height:132}}});}
let storage=null;const sandbox={World,console,Date,Math,JSON,innerWidth:960,performance:{now:()=>0},requestAnimationFrame(){},setInterval(){},setTimeout(f){timeouts.push(f);return timeouts.length},clearTimeout(){},addEventListener(n,f){events[n]=f},navigator:{getGamepads:()=>[]},localStorage:{getItem:()=>storage,setItem(k,v){storage=v}},document:{getElementById:el,querySelector:()=>null,createElement:()=>el('new'),querySelectorAll:()=>[],addEventListener(n,f){events[n]=f},activeElement:null}};vm.createContext(sandbox);vm.runInContext(fs.readFileSync('dist/play.js','utf8'),sandbox);vm.runInContext(fs.readFileSync('dist/interaction.js','utf8'),sandbox);const run=s=>vm.runInContext(s,sandbox);function frames(n){for(let i=0;i<n;i++)run('frame(prev+16.667)')}run('player.x=208;player.y=368');
events.keydown({key:'w',target:{tagName:'CANVAS'},preventDefault(){}});frames(75);assert(run('transitioning'));while(timeouts.length)timeouts.shift()();assert.equal(run('map.id'),'cottage','Walk into cottage changes area');assert.equal(run('player.y'),368);run('player.x=208;player.y=208;interact()');assert.equal(run('state.met'),true,'Nearby NPC can be spoken to');assert.equal(run('dialog'),true);const y=run('player.y');frames(10);assert.equal(run('player.y'),y,'Dialog pauses walking');run('close();map=worlds.meadow;player.x=18*T;player.y=21*T;interact()');assert.equal(run('encounter.name'),'Emberkin');run('close();state.last=Date.now()-3600000;state.bank.berries=0;accrue()');assert.equal(run('Math.floor(state.bank.berries)'),180);run('state.last=Date.now()-12*3600000;state.bank.berries=0;accrue()');assert.equal(run('Math.floor(state.bank.berries)'),1440);run('save()');assert.equal(JSON.parse(storage).position.area,'meadow');
run('close();map=worlds.valley;player.x=500;player.y=530');
sandbox.navigator.getGamepads=()=>[{connected:true,axes:[1,0],buttons:Array.from({length:16},()=>({pressed:false}))}];
const beforePad=run('player.x');frames(20);assert(run('player.x')>beforePad+20,'Controller left stick moves player');
sandbox.navigator.getGamepads=()=>[];
events['joystick:pointerdown']({pointerId:1,clientX:105,clientY:66});const beforeTouch=run('player.x');frames(20);assert(run('player.x')>beforeTouch+20,'Touch stick moves player');events['joystick:pointerup']();const released=run('player.x');frames(10);assert.equal(run('player.x'),released,'Releasing joystick stops movement');
run("close();map=worlds.valley;const timber=map.objects.find(o=>o.type==='log');player.x=timber.x;player.y=timber.y+25;interact()");assert.equal(run('activity.o.type'),'log');const initialWood=run('state.wood');run('tickActivities(1)');assert.equal(run('state.wood'),initialWood);run('tickActivities(1)');assert.equal(run('state.wood'),initialWood+3);run('interact()');assert.equal(run('activity'),null,'Cooldown prevents duplicate collection');
run("map=worlds.meadow;const spot=map.objects.find(o=>o.type==='fish');player.x=spot.x;player.y=spot.y+24;interact();interact()");assert.equal(run('activity'),null,'Reeling too early cancels');const initialFish=run('state.fish');run('interact();tickActivities(2.5);interact()');assert.equal(run('state.fish'),initialFish+3,'Reel during bite awards fish');run("state.cooldowns[spot.id]=0;interact();tickActivities(4.5)");assert.equal(run('activity'),null,'Missed bite expires');run('interact();player.x+=12;tickActivities(.1)');assert.equal(run('activity'),null,'Walking away cancels action');
for(const [name,choices]of [['Emberkin',['toss','toss']],['Dewdrop',['still','hum']],['Lunamoth',['light','circle']]]){run(`encounter={name:'${name}',trust:0};socialChoice('invalid')`);assert.equal(run('encounter.trust'),0);for(const choice of choices)run(`socialChoice('${choice}')`);assert.equal(run('encounter.trust'),2,`${name} distinct trust sequence`);}
run("encounter={name:'Dewdrop',trust:1};socialChoice('splash')");assert.equal(run('encounter.trust'),0,'Wrong approach reduces trust');
// Inspect actual sprite draw calls: front has two eyes; back has neither and has a backpack.
run("var spriteRects=[];ctx.fillRect=(x,y,w,h)=>spriteRects.push({x,y,w,h,c:ctx.fillStyle});human(0,0,false,0,0)");assert.equal(run("spriteRects.filter(r=>r.c==='#253c39').length"),2);run('spriteRects=[];human(0,0,false,3,0)');assert.equal(run("spriteRects.filter(r=>r.c==='#253c39').length"),0);assert(run("spriteRects.some(r=>r.c==='#ac8758')"));assert(run('spriteRects.every(r=>r.y>=-33)'),'Smaller sprite height');
console.log('PASS: movement/portals/collision; timed gathering and cooldown; fishing early/success/missed bite; movement cancellation; three distinct creature approaches; trust penalty; two front eyes, no back eyes, backpack and smaller sprite; idle progression.');


