const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),S=require('./dist/systems.js');
function client(storage={},remote=null){let server=remote,revision=remote?5:0,account='alice',reloads=0;const state=S.clean({team:['Pip'],last:Date.now(),coins:80}),events={};const context={MossSystems:S,state,Date,JSON,Number,Error,AbortController,setTimeout,clearTimeout,dialog:false,saveMenu(){},renderSaveBadge(){},resetInput(){},location:{reload(){reloads++}},addEventListener(n,f){events[n]=f},localStorage:{getItem:k=>storage[k]||null,setItem(k,v){storage[k]=v}},fetch:async(url,options)=>{let status=200,data;if(options.method==='GET')data={save:server,revision,account};else{const b=JSON.parse(options.body);if(b.account!==account||b.revision!==revision){status=409;data={save:server,revision,account};}else{server=b.state;revision++;data={revision};}}return{ok:status===200,status,json:async()=>data};}};vm.createContext(context);vm.runInContext(fs.readFileSync('dist/save.js','utf8'),context);const run=s=>vm.runInContext(s,context);run('SaveStore.read()');return{run,context,storage,events,get server(){return server},get reloads(){return reloads},external(s){server=s;revision++}};}
(async()=>{
const c=client();await c.run('SaveStore.sync(true)');assert.equal(c.server.coins,80);assert.equal(JSON.parse(c.storage['mosswild-save-v2']).cloud.account,'alice');c.external({...c.server,coins:200});c.context.state.coins=90;await c.run('SaveStore.sync(true)');assert(c.run('SaveStore.status().conflict'));assert.equal(c.server.coins,200);await c.run("SaveStore.choose('device')");assert.equal(c.server.coins,90);assert(!c.run('SaveStore.status().conflict'));
const d=client({},S.clean({team:['Pip'],last:Date.now(),coins:999}));await d.run('SaveStore.sync(true)');assert(d.run('SaveStore.status().conflict'));await d.run("SaveStore.choose('cloud')");assert.equal(d.reloads,1);d.run('SaveStore.write(state)');assert.equal(JSON.parse(d.storage['mosswild-save-v2']).state.coins,999,'pagehide must not overwrite restored cloud progress');
const e=client();e.run('SaveStore.write(state)');assert(e.run('SaveStore.replace({...state,coins:123})'));e.run('SaveStore.write(state)');assert.equal(JSON.parse(e.storage['mosswild-save-v2']).state.coins,123);assert.equal(e.run('SaveStore.recovery().coins'),80);
const future=JSON.stringify({schema:99,state:c.context.state}),f=client({'mosswild-save-v2':future});assert(f.run('SaveStore.status().blocked'));f.run('SaveStore.write(state)');assert.equal(f.storage['mosswild-save-v2'],future);
const offline=client();offline.context.fetch=async()=>{throw Error('Offline')};await offline.run('SaveStore.sync(true)');assert.match(offline.run('SaveStore.status().cloud'),/Offline/);assert(offline.run('SaveStore.write(state)'));
console.log('PASS: client cloud sync, conflict choice, account metadata, restore vs pagehide race, recovery preservation, future-version protection and offline local save.');
})().catch(e=>{console.error(e);process.exitCode=1});
