const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),S=require('./dist/systems.js');
const now=Date.now(),seed={coins:80,berries:5,wood:30,fish:3,crystals:9,xp:0,team:['Pip'],jobs:{Pip:'berries'},bank:{berries:0},last:now,upgrade:1};
const s=S.clean(seed,now);assert.equal(s.life.seeds,6);assert.equal(S.level(s,'Pip'),1);assert(S.plant(s,0,'turnip',now));assert(!S.plant(s,0,'turnip',now));assert(!S.harvest(s,0,now+30000));s.life.plots[0].watered=true;assert(S.harvest(s,0,now+59000));assert.equal(s.life.turnips,3);assert(!S.harvest(s,0,now+60000));assert(S.craft(s,'treat'));assert.equal(s.life.treats,1);assert.equal(s.life.treatsMade,1);assert(!S.craft(s,'treat'));assert(S.craft(s,'tool'));assert(!S.craft(s,'tool'));assert.equal(s.life.tools,1);assert(!S.claim(s,0));s.met=true;assert(S.claim(s,0));assert(!S.claim(s,0));assert(!S.claim(s,2));assert.equal(s.coins,40);
assert.throws(()=>S.unpack('{oops'));assert.throws(()=>S.unpack({schema:99,state:seed}));assert.throws(()=>S.clean({}));const safe=S.clean({...seed,coins:-5,position:{area:'valley',x:null,y:Infinity},life:{bond:{Pip:Infinity},plots:{'__proto__':{},0:{crop:'bad'}}}},now);assert.equal(safe.coins,0);assert.equal(safe.position.y,368);assert.equal(safe.life.bond.Pip,0);assert.deepEqual(safe.life.plots,{});
// Real game integration in a small DOM harness: scripts load, crop actions, rendering,
// migration, away accrual, local corruption recovery and save failures.
function harness(storage={}){const elements={},ctx=new Proxy({},{get:(t,k)=>k in t?t[k]:()=>{}}),handlers={};function el(id=''){return elements[id]??={innerHTML:'',textContent:'',style:{},dataset:{},clientWidth:390,clientHeight:844,classList:{add(){},remove(){},toggle(){}},getContext:()=>ctx,addEventListener(n,f){(handlers[id+':'+n]??=[]).push(f)},setAttribute(){},querySelector:()=>({focus(){}}),append(){},remove(){},focus(){},getBoundingClientRect:()=>({left:0,top:0,width:120,height:120})};}
 const base=require('./dist/world.js'),exp=require('./dist/expansion-world.js'),fw=require('./dist/frontier-world.js'),fc=require('./dist/frontier-core.js');const sandbox={World:{...base,createWorld:()=>fw.expand(exp.expand(base.createWorld()))},ExpansionWorld:exp,FrontierWorld:fw,FrontierCore:fc,GameAudio:{sfx(){},unlock:async()=>true,settings:{music:false,effects:true,volume:.3}},console,Date,Math,JSON,AbortController,innerWidth:390,performance:{now:()=>0},requestAnimationFrame(){},setInterval(){},setTimeout(){},clearTimeout(){},addEventListener(n,f){(handlers[n]??=[]).push(f)},matchMedia:()=>({matches:true}),navigator:{getGamepads:()=>[]},localStorage:{getItem:k=>storage[k]||null,setItem(k,v){storage[k]=v}},fetch:async()=>({status:404}),document:{getElementById:el,querySelector:()=>el('query'),querySelectorAll:()=>[],createElement:()=>el('new'),addEventListener(){}}};vm.createContext(sandbox);for(const file of ['systems.js','save.js','play.js','interaction.js','expansion.js','life.js','art.js','hud.js','frontier.js'])vm.runInContext(fs.readFileSync('dist/'+file,'utf8'),sandbox,{filename:file});return {run:s=>vm.runInContext(s,sandbox),storage,handlers,sandbox};}
const h=harness({'mosswild-save-v1':JSON.stringify({...seed,last:now-12*3600000})});assert(h.run('state.bank.berries')<=1440.1);assert(h.run('state.bank.berries')>=1440);h.run('frame(16.7);bag();help();adventureMenu();companionMenu();saveMenu();upgradeDialog();mapPanel();appearance()');assert.equal(h.run('worlds.valley.objects.filter(o=>o.type==="plot").length'),6);
h.run('dialog=false;map=worlds.valley;player.x=24*32+16;player.y=24*32;interact()');assert(h.run('dialog'));assert(h.run('nearest().type')==='plot');h.run("close();activity={o:worlds.valley.objects.find(o=>o.type==='berries'),elapsed:1,duration:1};state.life.bond.Pip=96;completeActivity()");assert.equal(h.run('MossSystems.level(state,"Pip")'),2);assert.equal(h.run('state.life.bond.Pip'),108);assert(h.storage['mosswild-save-v2']);
h.run("state.life.visits.push('orchard');state.life.claimed=[0,1,2,3,4,5,6,7];taskTab='story';adventureMenu();taskTab='requests';adventureMenu();taskTab='projects';adventureMenu();friendTab='trips';companionMenu();map=worlds.orchard;F.accept(state,'orchard');activity={o:map.objects.find(o=>o.type==='herb'),elapsed:2,duration:1};completeActivity();frame(33)");assert(h.run('state.frontier.gathered.herbs')>=2);h.run('state.frontier.avatar.coat=2;save()');assert.equal(JSON.parse(h.storage['mosswild-save-v2']).state.frontier.avatar.coat,2);
const recovered=harness({'mosswild-save-v2':'broken','mosswild-save-v2-recovery':h.storage['mosswild-save-v2']});assert.equal(recovered.run('state.life.bond.Pip'),120);assert.doesNotThrow(()=>JSON.parse(recovered.storage['mosswild-save-v2']));
const bad=harness({'mosswild-save-v2':'broken'});assert(bad.run('SaveStore.status().blocked'));assert.equal(bad.storage['mosswild-save-v2'],'broken');h.sandbox.localStorage.setItem=()=>{throw Error('Quota')};h.run('save()');assert.match(h.run('SaveStore.status().problem'),/failed/);
console.log('PASS: crop growth/harvest, recipe costs, companion levels, one-time chapter rewards, migration/validation, 8-hour away cap, full game loading/rendering, recovery and quota failures.');


